<div class="card mb-20"><div class="card-header split-header"><h2>Report Window</h2><div class="muted">Choose a recent period to refresh the summaries below</div></div><div class="card-body"><form method="get" action="<?= e(base_url('reports/stats')) ?>" class="filter-grid"><label class="form-label small-width"><span>Days</span><select name="days" class="form-input"><?php foreach ([7, 14, 30, 60, 90, 180, 365] as $window): ?><option value="<?= e((string) $window) ?>" <?= (int) $days === $window ? 'selected' : '' ?>>Last <?= e((string) $window) ?> days</option><?php endforeach; ?></select></label><div class="filter-actions full-width"><button type="submit" class="btn btn-primary">Refresh Report</button><a href="<?= e(base_url('inquiries')) ?>" class="btn">Open Inquiry List</a></div></form></div></div>

<div class="stats-grid stats-grid-five">
    <div class="card stat-card"><div class="stat-label">Total</div><div class="stat-value"><?= e((string) ($overview['total_count'] ?? 0)) ?></div></div>
    <div class="card stat-card"><div class="stat-label">Unread</div><div class="stat-value"><?= e((string) ($overview['unread_count'] ?? 0)) ?></div></div>
    <div class="card stat-card"><div class="stat-label">Assigned</div><div class="stat-value"><?= e((string) ($overview['assigned_count'] ?? 0)) ?></div></div>
    <div class="card stat-card"><div class="stat-label">Sites</div><div class="stat-value"><?= e((string) ($overview['site_count'] ?? 0)) ?></div></div>
    <div class="card stat-card"><div class="stat-label">Forms</div><div class="stat-value"><?= e((string) ($overview['form_count'] ?? 0)) ?></div></div>
</div>

<div class="dashboard-grid mt-20"><section class="card"><div class="card-header split-header"><h2>Recent Trend</h2><span class="muted">Showing up to the latest 30 days</span></div><div class="card-body"><?php $maxTrend = 1; foreach ($trendRows as $trendItem) { $maxTrend = max($maxTrend, (int) $trendItem['total_count']); } ?><div class="trend-list"><?php foreach ($trendRows as $trend): ?><div class="trend-row"><div class="trend-meta"><strong><?= e($trend['label']) ?></strong><span class="muted">T <?= e((string) $trend['total_count']) ?> · U <?= e((string) $trend['unread_count']) ?> · S <?= e((string) $trend['spam_count']) ?></span></div><div class="trend-bar-bg"><div class="trend-bar" style="width: <?= e((string) max(8, (int) round(($trend['total_count'] / $maxTrend) * 100))) ?>%"></div></div></div><?php endforeach; ?></div></div></section><section class="card"><div class="card-header"><h2>Status Breakdown</h2></div><div class="card-body compact-list"><?php foreach ($statusRows as $row): ?><div class="simple-list-item compact-item"><div class="split-header"><div class="simple-list-title"><?= e(ucfirst($row['status'])) ?></div><span class="status-pill status-<?= e($row['status']) ?>"><?= e((string) $row['total_count']) ?></span></div></div><?php endforeach; ?></div></section></div>

<div class="dashboard-grid dashboard-grid-3 mt-20"><section class="card"><div class="card-header"><h2>Top Sites</h2></div><div class="card-body compact-list"><?php foreach ($siteRows as $row): ?><div class="simple-list-item compact-item"><div class="simple-list-title"><?= e($row['site_name']) ?></div><div class="simple-list-meta"><?= e($row['site_domain']) ?> · <?= e((string) $row['total_count']) ?> total · <?= e((string) $row['unread_count']) ?> unread · <?= e((string) $row['spam_count']) ?> spam</div><div class="simple-list-meta mt-8">Last inquiry: <?= e((string) ($row['last_inquiry_at'] ?: '-')) ?></div></div><?php endforeach; ?></div></section><section class="card"><div class="card-header"><h2>Top Forms</h2></div><div class="card-body compact-list"><?php foreach ($formRows as $row): ?><div class="simple-list-item compact-item"><div class="simple-list-title"><?= e($row['form_key']) ?></div><div class="simple-list-meta"><?= e($row['site_name']) ?> · <?= e((string) $row['total_count']) ?> total · <?= e((string) $row['unread_count']) ?> unread</div><div class="simple-list-meta mt-8">Last inquiry: <?= e((string) ($row['last_inquiry_at'] ?: '-')) ?></div></div><?php endforeach; ?></div></section><section class="card"><div class="card-header"><h2>Top Countries</h2></div><div class="card-body compact-list"><?php foreach ($countryRows as $row): ?><div class="simple-list-item compact-item"><div class="simple-list-title"><?= e($row['country_name']) ?></div><div class="simple-list-meta"><?= e((string) $row['total_count']) ?> inquiries</div></div><?php endforeach; ?></div></section></div>

<div class="card mt-20"><div class="card-header"><h2>Assignee Summary</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Owner</th><th>Total</th><th>Unread</th><th>Spam</th></tr></thead><tbody><?php if (empty($assigneeRows)): ?><tr><td colspan="4" class="empty-cell">No assignment data yet.</td></tr><?php else: ?><?php foreach ($assigneeRows as $row): ?><tr><td><?= e($row['assignee_name']) ?></td><td><?= e((string) $row['total_count']) ?></td><td><?= e((string) $row['unread_count']) ?></td><td><?= e((string) $row['spam_count']) ?></td></tr><?php endforeach; ?><?php endif; ?></tbody></table></div></div>
